version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking Java & Maven"
      - java -version
      - mvn -version
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Spring Boot jar"
      - mvn clean package -DskipTests
      - echo "Building Docker image"
      - docker build -t eureka-service .

  post_build:
    commands:
      - echo "Pushing image to ECR"
      - docker tag eureka-service:latest ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/eureka-service:latest
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/eureka-service:latest
