version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Maven project...
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t eureka-service .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging the Docker image...
      - docker tag eureka-service:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/eureka-service:latest
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/eureka-service:latest

artifacts:
  files:
    - '**/*'
